### ISSUE TITLE
Example using redis/sidekiq?

### ISSUE THREAD

**Issue by Onumis** [CircleCI-Public/circleci-demo-ruby-rails#14]
Redis and Sidekiq are very popular with Rails apps.

Would be nice to have them on the default config, having a branch with it, or just a note on the README.

**Comment by Onumis** [comment]
Fwiw:

```

jobs:
  build:
    docker:
      - image: redis:4.0

```

still I lost half an hour looking at random foruns to get to this rather simple solution
