### ISSUE TITLE
Example of using workflows?

### ISSUE THREAD

**Issue by stevenspiel** [CircleCI-Public/circleci-demo-ruby-rails#8]
Feature Request:

Could you please integrate workflows into the `.circleci/config.yml` file? I'm having all sorts of issues with running tests and caching and would love to see the suggested way to run tests with workflows and rails. Also, bundling with `2.0` takes about 4 minutes, whereas with `1.0` it was ~45 seconds.

This is what my config looks like:

```yml
defaults: &defaults
  working_directory: ~/myapp
  docker:
    - image: circleci/ruby:2.3-browsers
    - image: circleci/postgres:9.4.12-alpine
  tz: "/usr/share/zoneinfo/America/Los_Angeles"
  environment:
    - PGUSER: postgres
    - POSTGRES_USER: postgres
    - USER: postgres
    - SLACK_CHANNEL: 'ci'
    - WKHTMLTOPDF_PATH: '/usr/bin/wkhtmltopdf'

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      # Pull code from github
      - checkout

      # Install dependencies
      - run: sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x pdftk wkhtmltopdf

      # Restore bundle cache
      - type: cache-restore
        key: myapp-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: gem install --version '=3.16.14.19' libv8
      - run: bundle install --local

      # Store bundle cache
      - type: cache-save
        key: myapp-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # Save artifacts
      - type: store_test_results
        path: /tmp/test-results
  lint:
    <<: *defaults
    steps:
      - type: cache-restore
        key: myapp-{{ checksum "Gemfile.lock" }}
      - type: shell
        command: |
          bundle exec rspec --profile 10 --format Fuubar --format RspecJunitFormatter --out /tmp/test-results/rspec.xml $(circleci tests glob "spec/lint/**/*_spec.rb")
  models:
    <<: *defaults
    steps:
      - type: cache-restore
        key: myapp-{{ checksum "Gemfile.lock" }}
      - type: shell
        command: bundle exec rspec --profile 10 --format Fuubar --format RspecJunitFormatter --out /tmp/test-results/rspec.xml $(circleci tests glob "spec/models/**/*_spec.rb")
```

The build runs fine (even though bundling takes 4 minutes): 

<img width="1816" alt="screen shot 2017-07-03 at 5 07 36 pm" src="https://user-images.githubusercontent.com/1630091/27807925-3ba13c36-6012-11e7-8526-2c3141068749.png">

but the `lint` job fails

<img width="1826" alt="screen shot 2017-07-03 at 8 17 05 pm" src="https://user-images.githubusercontent.com/1630091/27810787-a6f55408-602c-11e7-81da-657887c46fce.png">

I get an error when restoring the cache:

```
Error computing cache key: template: cacheKey:1:18: executing "cacheKey" at <checksum "Gemfile.lo...>: error calling checksum: open /home/circleci/myapp/Gemfile.lock: no such file or directory
```

And I get an error running my specs

```
#!/bin/bash -eo pipefail
bundle exec rspec --profile 10 --format Fuubar --format RspecJunitFormatter --out /tmp/test-results/rspec.xml $(circleci tests glob "spec/lint/*_spec.rb")
Could not locate Gemfile or .bundle/ directory
Exited with code 10
```

What am I doing wrong?
